version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "db"
  db:
    image: "postgres:alpine"
    ports: 
      - "5432:5432"
    volumes:
      - "./dump.sql:/dump.sql"
