openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'Back2School API'
  description: 'An API that allows the management of school bureaucracy'
  contact:
    name: Middleware2018-PSS
    url: https://github.com/middleware2018-PSS/Services
    email: mail@example.com

servers:
  - url: https://dev.foo.com/v1
    description: Dev Server
  
  - url: https://prod.foo.com/v1
    description: Prod Server

paths:

### STUDENTS
  /students:
    $ref: 'paths/students.yaml#/students'
  /students/{student_id}:
    $ref: 'paths/students.yaml#/student'

### STUDENT::GRADES
  /students/{student_id}/grades:
    $ref: 'paths/student_grades.yaml#/student-grades'
  /students/{student_id}/grades/{grade_id}:
    $ref: 'paths/student_grades.yaml#/student-grade'

### STUDENT::PAYMENTS
  /students/{student_id}/payments:
    $ref: 'paths/student_payments.yaml#/student-payments'
  /students/{student_id}/payments/{payment_id}:
    $ref: 'paths/student_payments.yaml#/student-payment'

### PARENTS
  /parents:
    $ref: 'paths/parents.yaml#/parents'
  /parents/{parent_id}:
    $ref: 'paths/parents.yaml#/parent'

### PARENT::STUDENTS
  /parents/{parent_id}/students:
    $ref: 'paths/parent_students.yaml#/parent-students'
  /parents/{parent_id}/students/{student_id}:
    $ref: 'paths/parent_students.yaml#/parent-student'

### PARENT::APPOINTMENTS
  /parents/{parent_id}/appointments:
    $ref: 'paths/parent_appointments.yaml#/parent-appointments'
  /parents/{parent_id}/appointments/{appointments_id}:
    $ref: 'paths/parent_appointments.yaml#/parent-appointment'

### TEACHERS
  /teachers:
    $ref: 'paths/teachers.yaml#/teachers'
  /teachers/{teacher_id}:
    $ref: 'paths/teachers.yaml#/teacher'

### TEACHER::CLASSES
  /teacher/{teacher_id}/classes:
    $ref: 'paths/teacher_classes.yaml#/teacher-classes'
  /teacher/{teacher_id}/classes/{class_id}:
    $ref: 'paths/teacher_classes.yaml#/teacher-class'
  /teacher/{teacher_id}/classes/{class_id}/students:
    $ref: 'paths/teacher_classes.yaml#/teacher-students'
  /teacher/{teacher_id}/classes/{class_id}/subjects:
    $ref: 'paths/teacher_classes.yaml#/teacher-subjects'
  /teacher/{teacher_id}/classes/{class_id}/timetable:
    $ref: 'paths/teacher_classes.yaml#/teacher-timetable'

### TEACHER::APPOINTMENTS
  /teachers/{teacher_id}/appointments:
    $ref: 'paths/teacher_appointments.yaml#/teacher-appointments'
  /teachers/{teacher_id}/appointments/{appointments_id}:
    $ref: 'paths/teacher_appointments.yaml#/teacher-appointment'

### CLASSES
  /classes:
    $ref: 'paths/classes.yaml#/classes'
  /classes/{class_id}:
    $ref: 'paths/classes.yaml#/class'

#########################################################################################
#                                      COMPONENTS                                       #
#########################################################################################

components:
  schemas:
    $ref: 'components.yaml'
