openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'Back2School API'
  description: 'An API that allows the management of school bureaucracy'
  contact:
    name: Middleware2018-PSS
    url: https://github.com/middleware2018-PSS/Services
    email: mail@example.com

servers:
  - url: https://dev.foo.com/v1
    description: Dev Server
  
  - url: https://prod.foo.com/v1
    description: Prod Server

paths:

### AUTH
  /login:
    $ref: 'paths/auth.yaml#/login'

### STUDENTS
  /students:
    $ref: 'paths/students.yaml#/students'
  /students/{student_id}:
    $ref: 'paths/students.yaml#/student'

### PARENTS
  /parents:
    $ref: 'paths/parents.yaml#/parents'
  /parents/{parent_id}:
    $ref: 'paths/parents.yaml#/parent'

### TEACHERS
  /teachers:
    $ref: 'paths/teachers.yaml#/teachers'
  /teachers/{teacher_id}:
    $ref: 'paths/teachers.yaml#/teacher'

### CLASSES
  /classes:
    $ref: 'paths/classes.yaml#/classes'
  /classes/{class_id}:
    $ref: 'paths/classes.yaml#/class'

### SUBJECTS
  /subjects:
    $ref: 'paths/subjects.yaml#/subjects'
  /subjects/{subject_id}:
    $ref: 'paths/subjects.yaml#/subject'

### TIMETABLES
  /timetables:
    $ref: 'paths/timetables.yaml#/timetables'
  /timetables/{timetable_id}:
    $ref: 'paths/timetables.yaml#/timetable'

### GRADES
  /grades:
    $ref: 'paths/grades.yaml#/grades'
  /grades/{grade_id}:
    $ref: 'paths/grades.yaml#/grade'

### PAYMENTS
  /payments:
    $ref: 'paths/payments.yaml#/payments'
  /payments/{payment_id}:
    $ref: 'paths/payments.yaml#/payment'

### APPOINTMENTS
  /appointments:
    $ref: 'paths/appointments.yaml#/appointments'
  /appointments/{appointments_id}:
    $ref: 'paths/appointments.yaml#/appointment'


#########################################################################################
#                                      COMPONENTS                                       #
#########################################################################################

components:
  schemas:
    $ref: 'components.yaml'
