// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Subject is an object representing the database table.
type Subject struct {
	ID string `boil:"id" json:"id" toml:"id" yaml:"id"`

	R *subjectR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L subjectL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SubjectColumns = struct {
	ID string
}{
	ID: "id",
}

// subjectR is where relationships are stored.
type subjectR struct {
	Teaches    TeachSlice
	Timetables TimetableSlice
}

// subjectL is where Load methods for each relationship are stored.
type subjectL struct{}

var (
	subjectColumns               = []string{"id"}
	subjectColumnsWithoutDefault = []string{}
	subjectColumnsWithDefault    = []string{"id"}
	subjectPrimaryKeyColumns     = []string{"id"}
)

type (
	// SubjectSlice is an alias for a slice of pointers to Subject.
	// This should generally be used opposed to []Subject.
	SubjectSlice []*Subject
	// SubjectHook is the signature for custom Subject hook methods
	SubjectHook func(boil.Executor, *Subject) error

	subjectQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	subjectType                 = reflect.TypeOf(&Subject{})
	subjectMapping              = queries.MakeStructMapping(subjectType)
	subjectPrimaryKeyMapping, _ = queries.BindMapping(subjectType, subjectMapping, subjectPrimaryKeyColumns)
	subjectInsertCacheMut       sync.RWMutex
	subjectInsertCache          = make(map[string]insertCache)
	subjectUpdateCacheMut       sync.RWMutex
	subjectUpdateCache          = make(map[string]updateCache)
	subjectUpsertCacheMut       sync.RWMutex
	subjectUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var subjectBeforeInsertHooks []SubjectHook
var subjectBeforeUpdateHooks []SubjectHook
var subjectBeforeDeleteHooks []SubjectHook
var subjectBeforeUpsertHooks []SubjectHook

var subjectAfterInsertHooks []SubjectHook
var subjectAfterSelectHooks []SubjectHook
var subjectAfterUpdateHooks []SubjectHook
var subjectAfterDeleteHooks []SubjectHook
var subjectAfterUpsertHooks []SubjectHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Subject) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Subject) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Subject) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Subject) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Subject) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Subject) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Subject) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Subject) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Subject) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range subjectAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSubjectHook registers your hook function for all future operations.
func AddSubjectHook(hookPoint boil.HookPoint, subjectHook SubjectHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		subjectBeforeInsertHooks = append(subjectBeforeInsertHooks, subjectHook)
	case boil.BeforeUpdateHook:
		subjectBeforeUpdateHooks = append(subjectBeforeUpdateHooks, subjectHook)
	case boil.BeforeDeleteHook:
		subjectBeforeDeleteHooks = append(subjectBeforeDeleteHooks, subjectHook)
	case boil.BeforeUpsertHook:
		subjectBeforeUpsertHooks = append(subjectBeforeUpsertHooks, subjectHook)
	case boil.AfterInsertHook:
		subjectAfterInsertHooks = append(subjectAfterInsertHooks, subjectHook)
	case boil.AfterSelectHook:
		subjectAfterSelectHooks = append(subjectAfterSelectHooks, subjectHook)
	case boil.AfterUpdateHook:
		subjectAfterUpdateHooks = append(subjectAfterUpdateHooks, subjectHook)
	case boil.AfterDeleteHook:
		subjectAfterDeleteHooks = append(subjectAfterDeleteHooks, subjectHook)
	case boil.AfterUpsertHook:
		subjectAfterUpsertHooks = append(subjectAfterUpsertHooks, subjectHook)
	}
}

// OneP returns a single subject record from the query, and panics on error.
func (q subjectQuery) OneP() *Subject {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single subject record from the query.
func (q subjectQuery) One() (*Subject, error) {
	o := &Subject{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for subjects")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Subject records from the query, and panics on error.
func (q subjectQuery) AllP() SubjectSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Subject records from the query.
func (q subjectQuery) All() (SubjectSlice, error) {
	var o []*Subject

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Subject slice")
	}

	if len(subjectAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Subject records in the query, and panics on error.
func (q subjectQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Subject records in the query.
func (q subjectQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count subjects rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q subjectQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q subjectQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if subjects exists")
	}

	return count > 0, nil
}

// TeachesG retrieves all the teach's teaches.
func (o *Subject) TeachesG(mods ...qm.QueryMod) teachQuery {
	return o.Teaches(boil.GetDB(), mods...)
}

// Teaches retrieves all the teach's teaches with an executor.
func (o *Subject) Teaches(exec boil.Executor, mods ...qm.QueryMod) teachQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"back2school\".\"teaches\".\"subject\"=?", o.ID),
	)

	query := Teaches(exec, queryMods...)
	queries.SetFrom(query.Query, "\"back2school\".\"teaches\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"back2school\".\"teaches\".*"})
	}

	return query
}

// TimetablesG retrieves all the timetable's timetable.
func (o *Subject) TimetablesG(mods ...qm.QueryMod) timetableQuery {
	return o.Timetables(boil.GetDB(), mods...)
}

// Timetables retrieves all the timetable's timetable with an executor.
func (o *Subject) Timetables(exec boil.Executor, mods ...qm.QueryMod) timetableQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"back2school\".\"timetable\".\"subject\"=?", o.ID),
	)

	query := Timetables(exec, queryMods...)
	queries.SetFrom(query.Query, "\"back2school\".\"timetable\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"back2school\".\"timetable\".*"})
	}

	return query
}

// LoadTeaches allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (subjectL) LoadTeaches(e boil.Executor, singular bool, maybeSubject interface{}) error {
	var slice []*Subject
	var object *Subject

	count := 1
	if singular {
		object = maybeSubject.(*Subject)
	} else {
		slice = *maybeSubject.(*[]*Subject)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &subjectR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &subjectR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"back2school\".\"teaches\" where \"subject\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load teaches")
	}
	defer results.Close()

	var resultSlice []*Teach
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice teaches")
	}

	if len(teachAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Teaches = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.Subject {
				local.R.Teaches = append(local.R.Teaches, foreign)
				break
			}
		}
	}

	return nil
}

// LoadTimetables allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (subjectL) LoadTimetables(e boil.Executor, singular bool, maybeSubject interface{}) error {
	var slice []*Subject
	var object *Subject

	count := 1
	if singular {
		object = maybeSubject.(*Subject)
	} else {
		slice = *maybeSubject.(*[]*Subject)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &subjectR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &subjectR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"back2school\".\"timetable\" where \"subject\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load timetable")
	}
	defer results.Close()

	var resultSlice []*Timetable
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice timetable")
	}

	if len(timetableAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Timetables = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.Subject {
				local.R.Timetables = append(local.R.Timetables, foreign)
				break
			}
		}
	}

	return nil
}

// AddTeachesG adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Teaches.
// Sets related.R.Subject appropriately.
// Uses the global database handle.
func (o *Subject) AddTeachesG(insert bool, related ...*Teach) error {
	return o.AddTeaches(boil.GetDB(), insert, related...)
}

// AddTeachesP adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Teaches.
// Sets related.R.Subject appropriately.
// Panics on error.
func (o *Subject) AddTeachesP(exec boil.Executor, insert bool, related ...*Teach) {
	if err := o.AddTeaches(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTeachesGP adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Teaches.
// Sets related.R.Subject appropriately.
// Uses the global database handle and panics on error.
func (o *Subject) AddTeachesGP(insert bool, related ...*Teach) {
	if err := o.AddTeaches(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTeaches adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Teaches.
// Sets related.R.Subject appropriately.
func (o *Subject) AddTeaches(exec boil.Executor, insert bool, related ...*Teach) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Subject = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"back2school\".\"teaches\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"subject"}),
				strmangle.WhereClause("\"", "\"", 2, teachPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.Teacher, rel.Subject, rel.Class}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Subject = o.ID
		}
	}

	if o.R == nil {
		o.R = &subjectR{
			Teaches: related,
		}
	} else {
		o.R.Teaches = append(o.R.Teaches, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &teachR{
				Subject: o,
			}
		} else {
			rel.R.Subject = o
		}
	}
	return nil
}

// AddTimetablesG adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Timetables.
// Sets related.R.Subject appropriately.
// Uses the global database handle.
func (o *Subject) AddTimetablesG(insert bool, related ...*Timetable) error {
	return o.AddTimetables(boil.GetDB(), insert, related...)
}

// AddTimetablesP adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Timetables.
// Sets related.R.Subject appropriately.
// Panics on error.
func (o *Subject) AddTimetablesP(exec boil.Executor, insert bool, related ...*Timetable) {
	if err := o.AddTimetables(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTimetablesGP adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Timetables.
// Sets related.R.Subject appropriately.
// Uses the global database handle and panics on error.
func (o *Subject) AddTimetablesGP(insert bool, related ...*Timetable) {
	if err := o.AddTimetables(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddTimetables adds the given related objects to the existing relationships
// of the subject, optionally inserting them as new records.
// Appends related to o.R.Timetables.
// Sets related.R.Subject appropriately.
func (o *Subject) AddTimetables(exec boil.Executor, insert bool, related ...*Timetable) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Subject = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"back2school\".\"timetable\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"subject"}),
				strmangle.WhereClause("\"", "\"", 2, timetablePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Subject = o.ID
		}
	}

	if o.R == nil {
		o.R = &subjectR{
			Timetables: related,
		}
	} else {
		o.R.Timetables = append(o.R.Timetables, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &timetableR{
				Subject: o,
			}
		} else {
			rel.R.Subject = o
		}
	}
	return nil
}

// SubjectsG retrieves all records.
func SubjectsG(mods ...qm.QueryMod) subjectQuery {
	return Subjects(boil.GetDB(), mods...)
}

// Subjects retrieves all the records using an executor.
func Subjects(exec boil.Executor, mods ...qm.QueryMod) subjectQuery {
	mods = append(mods, qm.From("\"back2school\".\"subjects\""))
	return subjectQuery{NewQuery(exec, mods...)}
}

// FindSubjectG retrieves a single record by ID.
func FindSubjectG(id string, selectCols ...string) (*Subject, error) {
	return FindSubject(boil.GetDB(), id, selectCols...)
}

// FindSubjectGP retrieves a single record by ID, and panics on error.
func FindSubjectGP(id string, selectCols ...string) *Subject {
	retobj, err := FindSubject(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindSubject retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSubject(exec boil.Executor, id string, selectCols ...string) (*Subject, error) {
	subjectObj := &Subject{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"back2school\".\"subjects\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(subjectObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from subjects")
	}

	return subjectObj, nil
}

// FindSubjectP retrieves a single record by ID with an executor, and panics on error.
func FindSubjectP(exec boil.Executor, id string, selectCols ...string) *Subject {
	retobj, err := FindSubject(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Subject) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Subject) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Subject) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Subject) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no subjects provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(subjectColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	subjectInsertCacheMut.RLock()
	cache, cached := subjectInsertCache[key]
	subjectInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			subjectColumns,
			subjectColumnsWithDefault,
			subjectColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(subjectType, subjectMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(subjectType, subjectMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"back2school\".\"subjects\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"back2school\".\"subjects\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into subjects")
	}

	if !cached {
		subjectInsertCacheMut.Lock()
		subjectInsertCache[key] = cache
		subjectInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Subject record. See Update for
// whitelist behavior description.
func (o *Subject) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Subject record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Subject) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Subject, and panics on error.
// See Update for whitelist behavior description.
func (o *Subject) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Subject.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Subject) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	subjectUpdateCacheMut.RLock()
	cache, cached := subjectUpdateCache[key]
	subjectUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			subjectColumns,
			subjectPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update subjects, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"back2school\".\"subjects\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, subjectPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(subjectType, subjectMapping, append(wl, subjectPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update subjects row")
	}

	if !cached {
		subjectUpdateCacheMut.Lock()
		subjectUpdateCache[key] = cache
		subjectUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q subjectQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q subjectQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for subjects")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o SubjectSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o SubjectSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o SubjectSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SubjectSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), subjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"back2school\".\"subjects\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, subjectPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in subject slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Subject) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Subject) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Subject) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Subject) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no subjects provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(subjectColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	subjectUpsertCacheMut.RLock()
	cache, cached := subjectUpsertCache[key]
	subjectUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			subjectColumns,
			subjectColumnsWithDefault,
			subjectColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			subjectColumns,
			subjectPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert subjects, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(subjectPrimaryKeyColumns))
			copy(conflict, subjectPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"back2school\".\"subjects\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(subjectType, subjectMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(subjectType, subjectMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert subjects")
	}

	if !cached {
		subjectUpsertCacheMut.Lock()
		subjectUpsertCache[key] = cache
		subjectUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Subject record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Subject) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Subject record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Subject) DeleteG() error {
	if o == nil {
		return errors.New("models: no Subject provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Subject record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Subject) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Subject record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Subject) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Subject provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), subjectPrimaryKeyMapping)
	sql := "DELETE FROM \"back2school\".\"subjects\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from subjects")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q subjectQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q subjectQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no subjectQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from subjects")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o SubjectSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o SubjectSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Subject slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o SubjectSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SubjectSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Subject slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(subjectBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), subjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"back2school\".\"subjects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, subjectPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from subject slice")
	}

	if len(subjectAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Subject) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Subject) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Subject) ReloadG() error {
	if o == nil {
		return errors.New("models: no Subject provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Subject) Reload(exec boil.Executor) error {
	ret, err := FindSubject(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SubjectSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SubjectSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SubjectSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty SubjectSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SubjectSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	subjects := SubjectSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), subjectPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"back2school\".\"subjects\".* FROM \"back2school\".\"subjects\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, subjectPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&subjects)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SubjectSlice")
	}

	*o = subjects

	return nil
}

// SubjectExists checks if the Subject row exists.
func SubjectExists(exec boil.Executor, id string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"back2school\".\"subjects\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if subjects exists")
	}

	return exists, nil
}

// SubjectExistsG checks if the Subject row exists.
func SubjectExistsG(id string) (bool, error) {
	return SubjectExists(boil.GetDB(), id)
}

// SubjectExistsGP checks if the Subject row exists. Panics on error.
func SubjectExistsGP(id string) bool {
	e, err := SubjectExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// SubjectExistsP checks if the Subject row exists. Panics on error.
func SubjectExistsP(exec boil.Executor, id string) bool {
	e, err := SubjectExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
